### ISSUE TITLE
Local config is overwritten on every fetch

### ISSUE THREAD

**Issue by wimvds** [Kunstmaan/skylab#68]
Even when you already have the project installed, the local config will be overwritten when you fetch the project from a server. This breaks the current config, so you have to manually restore it again (when you have multiple domains and domain determines language).

**Comment by krispypen** [comment]
Don't really know a solution here, because in other cases you want the latest config to be fetched. That is also what I expect.

Maybe there needs to be a "diff wizard" which ask what you want to override or not?

**Comment by kimausloos** [comment]
I propose we add a --skip-config flag that adds the relevant directories to the rsync ignore...

**Comment by roderik** [comment]
I think the solution is more simple, we add the ability to wok with ".local" files. The newserver branch already has logic for the .dist files, it can as easily prefer .local versions over other available ones. *.local should be gitignored ofcourse. In the newserver branch we can remove the config sync completely, because they are in git.

**Comment by roderik** [comment]
Added in e913349fb79303e78c2b4c1b07b1b41cd0fc9fc0
